=== prupp/xml/packages/packages.xsd
<xs:schema attributeFormDefault="unqualified" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">
  <xs:element name="packages">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="package" maxOccurs="unbounded" minOccurs="0">
          <xs:complexType>
            <xs:sequence>
              <xs:element type="xs:byte" name="price"/>
              <xs:element type="xs:string" name="description"/>
			  <xs:element type="xs:string" name="wine"/>
              <xs:element name="picture">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute type="xs:string" name="href" use="optional"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute type="xs:string" name="name" use="optional"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>

=== prupp/xml/packages/packages.xml
<?xml version="1.0" encoding="UTF-8"?>
<?xml-stylesheet type="text/xsl" href="packages.xsl"?>
<packages xsi:noNamespaceSchemaLocation="packages.xsd" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance">

	<package name="Das romantische Fass">
		<price>100</price>
		<description>Das romantische Fass ist vollkommen auf die getraute Zweisamkeit ausgelegt. Geniessen Sie Ihren speziellen Tag an einem ungewöhnlichen Ort. <br/>Statt Wein wird der Besuch mit einer Flasche Champagner begleitet.</description>
		<wine>1 Flasche Champagner</wine>
		<picture href="images/romantic.jpg"/>
	</package>
	<package name="Das Familien-Fass">
		<price>60</price>
		<description>Sehr familiär. Unser grösstes Fass bietet Platz für 4. Begeben Sie sich auf ein Familienabenteuer in unserem Fass. Für die Älteren Gäste gibt es eine Flasche Rot/oder Weisswein und für die jüngeren eine Flasche Rimuss.</description>
		<wine>1 Flasche Pino Noir, 1 Flasche Rimuss</wine>
		<picture href="images/family.jpg"/>
	</package>
	<package name="Das einfache Fass">
		<price>40</price>
		<description>Sehr einfach. Ein Fass für Aussteiger. Bewusst gibt es keine Steckdosen . Eine Laterne spendet Licht wenn es dunkel wird. In diesem Fass ist man einfach mal Offline.</description>
		<wine>1 Flasche Cornalin</wine>
		<picture href="images/simple.jpg"/>
	</package>
	<package name="Das entspannende Fass">
		<price>50</price>
		<description>Very Relaxing</description>
		<wine>1 Flasche Amarone</wine>
		<picture href="images/relax.jpg"/>
	</package>

</packages>
